# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 10000

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
[â•­â•´](#75d7ec)$env_var\
$all[â•°â”€](bold green)$character"""

# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ](bold red)"
vimcmd_symbol = "[âœ](bold green)"
vimcmd_replace_one_symbol = "[âœ](bold purple)"
vimcmd_replace_symbol = "[âœ](bold purple)"
vimcmd_visual_symbol = "[âœ](bold yellow)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Node.js
[nodejs]
format = "via [â¬¢ $version](bold green) "

# Golang
[golang]
format = "via [ğŸğŸ’¨ $version](bold cyan) "
